---
- name: create config folder locally
  file: path=config/{{ inventory_hostname }} state=directory recurse=yes
  delegate_to: localhost

- name: locally render interfaces template
  template:
    src=interfaces.j2
    dest=config/{{ inventory_hostname }}/interfaces
  delegate_to: localhost


- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  notify: reload networking

