---
- hosts: leaf,spine,exit
  become: true
  gather_facts: false
  tasks:
    - name: Apply Netq repos
      apt_repository:
        repo: deb http://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 netq-latest
        state: present

    - name: Install Netq packages
      apt:
        name: cumulus-netq
        update_cache: yes
        state: latest

    - name: Configure Netq Server
      shell: /usr/bin/netq config add server 192.168.6.250 vrf mgmt

    - name: Restart Netq agent to apply config
      shell: /usr/bin/netq config restart agent

    - name: Start Netq agent
      shell: /usr/bin/netq config start agent
