---
- name: Copy FRR daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
  notify: restart frr

- name: L4 hash policy
  sysctl:
    name: net.ipv4.fib_multipath_hash_policy
    value: 1
    state: present

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  notify: reload networking

- name: Copy FRR configuration
  template:
    src: frr.j2
    dest: /etc/frr/frr.conf
  notify: reload frr

#- name: install netq
#  template:
#    src: source_list.j2
#    dest: /etc/apt/sources.list
#  notify: install netq

- name: configure and activate netq
  template:
    src: netq.j2
    dest: /etc/netq/netq.yml
  notify: activate netq

