---
#- name: Copy FRR daemons file
#  copy:
#    src: daemons
#    dest: /etc/frr/daemons
#  notify: restart frr
#
#- name: L4 hash policy
#  sysctl:
#    name: net.ipv4.fib_multipath_hash_policy
#    value: 1
#    state: present
#
#- name: Copy interfaces configuration
#  template:
#    src: interfaces.j2
#    dest: /etc/network/interfaces
#  notify: reload networking
#
#- name: Copy FRR configuration
#  template:
#    src: frr.j2
#    dest: /etc/frr/frr.conf
#  notify: reload frr

- name: create config folder locally
  file: path=config/{{ inventory_hostname }} state=directory recurse=yes
  delegate_to: localhost

- name: locally render FRR template
  template:
    src=frr.j2
    dest=config/{{ inventory_hostname }}/frr.conf
  delegate_to: localhost

- name: locally render interfaces template
  template:
    src=frr.j2
    dest=config/{{ inventory_hostname }}/interfaces
  delegate_to: localhost
