---
# Modifies the Cumulus forwarding profile
# Also modifies the kernel parameters for L4 neighbor entries

- hosts: leaf
  become: yes
  gather_facts: yes
  tasks:
    - name: Sysctl net.ipv4.neigh.default.gc_thresh2
      sysctl:
            name: net.ipv4.neigh.default.gc_thresh2
            value: 78000
            state: present
            reload: no
    - name: Sysctl net.ipv4.neigh.default.gc_thresh3
      sysctl:
            name: net.ipv4.neigh.default.gc_thresh3
            value: 80000
            state: present
            reload: no
    - name: Reloads sysctl
      shell: sysctl -p
    - name: Reload switchd
      shell: systemctl restart switchd
