---
- hosts: leaf,spine,exit
  become: yes
  gather_facts: yes
  tasks:
	- name: Sysctl net.ipv4.neigh.default.gc_thresh2
  		sysctl:
    		name: net.ipv4.neigh.default.gc_thresh2
    		value: 74375
    		state: present
    		reload: no
	- name: Sysctl net.ipv4.neigh.default.gc_thresh3
  		sysctl:
    		name: net.ipv4.neigh.default.gc_thresh3
    		value: 85000
    		state: present
    		reload: yes