---
name: "exit01"
profile: "exit"
asn: 4200502000
routing:
  bgp:
    vrf:
      public:
         br_rt01:
            ipv4_address: "185.2.139.137"
            ipv6_address: "2A02:2498:E004:1F::1"
            asn: 13213          
      Customer_A:
         edgert01:
            ipv4_address: "10.1.1.1"
            ipv6_address: "2A02:2498:E004:8F::1"
            asn: 65150
      Customer_B:
         edgert01:
            ipv4_address: "10.2.2.1"
            ipv6_address: "2A02:2498:E004:9F::1"
            asn: 65150

vrf:
  list:
    - "public"
    - "Customer_A"
    - "Customer_B"
svi:
  interfaces:
    vlan4001:
      svi_type: "vxlan"
      vlan_id: 4001
      vrf: "public"
    vlan200:
      svi_type: "vxlan"
      vlan_id: 200
      vrf: "Customer_A"
    vlan300:
      svi_type: "vxlan"
      vlan_id: 300
      vrf: "Customer_B"

bridge:
  bridge_ports:
    - "vxlan4001"
    - "vxlan200"
    - "vxlan300"
  bridge_vids:
    - 4001
    - 200
    - 300

vxlan:
  interfaces:
    vxlan4001:
      vni_type: "l3"
      vlan_id: 4001
      vxlan_id: 104001
      vrf: "public"
    vxlan200:
      vni_type: "l3"
      vlan_id: 200
      vxlan_id: 10200
      vrf: "Customer_A"
    vxlan300:
      vni_type: "l3"
      vlan_id: 300
      vxlan_id: 10300
      vrf: "Customer_B"


lo:
  ipv4: "10.0.0.41"
eth0:
  ipv4: "10.0.3.41/25"
  ipv4_gateway: "10.0.3.1"
interfaces:
  swp32:
    description: "border router"
    port_type: "edge"
    ipv4_address: "185.2.139.136/31"
    ipv6_address: "2A02:2498:E004:1F::2/64"
    vrf: "public"

  swp1:
    description: "spine01"
    port_type: "uplink"
  swp2:
    description: "spine02"
    port_type: "uplink"
  swp3:
    description: "spine03"
    port_type: "uplink"
  swp4:
    description: "spine04"
    port_type: "uplink"

