---
  - name: Enable BGP
    nclu:
      commands:
        - add loopback lo ip address {{ loopback }}
        - add bgp autonomous-system {{ asn }}
        - add bgp router-id {{ rid }}
        - add bgp bestpath as-path multipath-relax
        - add bgp neighbor {{ item }} interface remote-as external
        - add bgp l2vpn evpn vni 10100 rd {{ rid }}:100
        - add bgp l2vpn evpn neighbor {{ item }} activate
        - add bgp evpn vni 10100 route-target both 100:100
        - add bgp l2vpn evpn advertise-all-vni
        - add bgp network {{ loopback }}
      atomic: true
      description: "Enable BGP"
    with_items: "{{ bgp_neighbour_ports }}"
