---
- name: locally render template
  template: src=spine_interfaces.j2 dest=./config/{{ inventory_hostname }}/interfaces
  delegate_to: localhost

- name: render template on remote remote host
  template: src=spine_interfaces.j2 dest=/etc/network/interfaces
  notify:
    - reload networking
