---
- hosts: leaf,spine,exit,oob-switch
  become: yes
  tasks:
  - name: Backup interfaces
    fetch: src=/etc/network/interfaces dest=./flatfiles/{{ansible_hostname}}/interfaces flat=yes

  - name: Backup daemons
    fetch: src=/etc/frr/daemons dest=./flatfiles/{{ansible_hostname}}/daemons flat=yes

  - name: Backup frr
    fetch: src=/etc/frr/frr.conf dest=./flatfiles/{{ansible_hostname}}/frr.conf flat=yes

  - name: Backup Cumulus ports
    fetch: src=/etc/cumulus/ports.conf dest=./flatfiles/{{ansible_hostname}}/ports.conf flat=yes

  - name: Backup over MTU json
    fetch: src=/etc/network/ifupdown2/policy.d/mtu.json dest=./flatfiles/{{ansible_hostname}}/mtu.json flat=yes
