---
- hosts: leaf,exit,spine
  become: yes
  tasks:
  - name: stop snmpd
    shell: systemctl stop snmpd.service

  - name: disable snmpd
    shell: systemctl disable snmpd.service

  - name: start snmpd in mgmt vrf
    shell: systemctl start snmpd@mgmt.service

  - name: enable snmpd in mgmt vrf
    shell: systemctl enable snmpd@mgmt.service
